### ISSUE TITLE
Module not found: Error: Can't resolve 'react' in

### ISSUE THREAD

**Issue by shuyue426** [unadlib/fronts#29]
**Try run the examples/basic app4,it throw error as :**
ERROR in ./src/Button.tsx 1:0-31
Module not found: Error: Can't resolve 'react' in '/Users/xxx/Downloads/fronts-master/examples/basic/app4/src'
 @ ./src/App.tsx 2:0-35 4:152-163
 @ ./src/bootstrap.tsx 4:0-24 6:52-55
 @ ./src/index.ts 1:0-21

ERROR in ./src/bootstrap.tsx 1:0-26
Module not found: Error: Can't resolve 'react' in '/Users/xxx/Downloads/fronts-master/examples/basic/app4/src'
 @ ./src/index.ts 1:0-21

ERROR in ./src/bootstrap.tsx 3:0-36
Module not found: Error: Can't resolve 'fronts-react' in '/Users/xxx/Downloads/fronts-master/examples/basic/app4/src'
 @ ./src/index.ts 1:0-21

ERROR in ../node_modules/react-dom/cjs/react-dom.development.js 18:12-28
Module not found: Error: Can't resolve 'react' in '/Users/xxx/Downloads/fronts-master/examples/basic/node_modules/react-dom/cjs'
 @ ../node_modules/react-dom/index.js 37:2-60
 @ ./src/bootstrap.tsx 2:0-33 6:2-17 8:4-35
 @ ./src/index.ts 1:0-21

What need to do to make example/basic works,thank you.

**Comment by unadlib** [comment]
Hi @shuyue426 , you must execute `yarn build` in the root directory, and `cd example/basic && yarn install`.

**Comment by shuyue426** [comment]
it works,thanks.
